### PR TITLE
about pokemon draft 1

### PR DESCRIPTION
**Pull request by yerwhile**
Concerns:

Styling of title "About Gym"

Positioning of image within its parent border-box.

### CODE REVIEW

**Review by will-hedges — CHANGES_REQUESTED** [review]
Looks great so far, but we should probably but the "About" section below the trainer section.

**Review by kaci-wooldridge — APPROVED** [review]
top notch

**Review by will-hedges — APPROVED** [review]
Awesome job!

**Review by devans0507 — APPROVED** [review]
perfect

**Review by kaci-wooldridge — APPROVED** [review]
🥇

**Pull request merged**
