### PR TITLE
added layout + trainer pokemon

### PR DESCRIPTION
**Pull request by will-hedges**
* added some basic styling
* uploaded wireframe

### CODE REVIEW

**Review by devans0507 — APPROVED** [review]
noice

**Review by yerwhile — APPROVED** [review]
thumbs up

**Review by yerwhile — CHANGES_REQUESTED** [review]
Change Kaci's motto (but maybe not).

**Review by kaci-wooldridge — CHANGES_REQUESTED** [review]
placeholder => "surrender now, or prepare to fight"

**Review by yerwhile — APPROVED** [review]
well ok

**Review by kaci-wooldridge — CHANGES_REQUESTED** [review]
wooldridge

**Review by kaci-wooldridge — APPROVED** [review]
good enough

**Pull request merged**
